### ISSUE TITLE
Checklist for Published Write-up

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/snap-it-up#44]
#### BLUF:

It's time to ship! We are presenting our work in Boston on April 1st at Health Refactored, a health and technology conference, where Code for America is included on a panel about equity in health.

In parallel with that presentation, we want to publish our narrative write up of the work completed to date and the human impact of the problem we are investigating, as eloquently outlined by @bengolder in #6.

We have a good amount of work left to do, so let's use this thread as a way to coordinate that work across contributors over the next week.

The write up itself (as in _the content_), and the presentation, need to ship by March 25th. We want to ship the full experience by the presentation date, which is April 1st.

Cc'ing all the current and future contributors. Please edit, amend or improve the list below. We can also talk about trimming the scope based on our time and availability.
@lippytak @Mr0grog @bengolder @davidrleonard @bensheldon 
#### Narrative
- [x] Type and share notes from interview of the Food Bank of San Francisco and Marin.
  - [x] @bengolder 
  - [x] @alanjosephwilliams
- [ ] Solicit comment from public information officers of Tennessee, Louisiana and Indiana (states with 0% downtime) about downtime.
  - [x] Louisiana @alanjosephwilliams
  - [x] Tennessee @alanjosephwilliams
  - [x] Indiana @alanjosephwilliams
- [x] Type interview notes of SNAP outreach workers in other states
  - [x] Food Bank of New Orleans @alanjosephwilliams
  - [x] Food Bank of Mid-Tennessee @alanjosephwilliams
- [x] Contact and Interview other SNAP outreach and Food Banks
  - [x] Food Bank of Western Mass 
    - [x] Contacted @alanjosephwilliams
    - [x] Interviewed @alanjosephwilliams
  - [ ] Community Health Advocates (Tennessee)
    - [x] Contacted @alanjosephwilliams
    - [ ] Interviewed @alanjosephwilliams
- [ ] Author first draft of the narrative @bengolder @alanjosephwilliams
- [ ] Editing and second and third drafts @bengolder @alanjosephwilliams
#### Graphics without data
- [x] Portrait of Liliana @alanjosephwillliams
- [x] Portrait of Xiao in fetal position @alanjosephwilliams
- [ ] Handwritten/drawn excerpts of hilariously bad copywriting on error pages @alanjosephwilliams
- [ ] Text Message exchanges @alanjosephwilliams
#### Data Visualizations
- [x] Map of current downtime 
- [x] Map of downtime over the last week
- [x] Implement better color scheme for the map per #45 
- [ ] Exploration of how to display screenshots of error/down pages. @Mr0grog 
- [ ] Animated Map of downtime over our best month of data @Mr0grog 
#### Presentation
- [x] Presentation Outline
- [x] Adapt narrative and graphics for 20 minute presentation.
- [x] Discuss and confirm overarching calls to action.
#### Research
- [ ] Historical uptime for comparables like Google, Banks, Credit Unions, the SEC, CNN, etc.
#### Front-end
- [ ] Call to action - Send a letter customized for your area code or state. @davidrleonard 
- [ ] Dynamic headline for the article based on current or recent downtime. @Mr0grog 
- [x] Subdomain on codeforamerica.org @davidrleonard 
- [ ] Twitter/FB card configuration 
- [ ] Typography
#### Technical write-up
- [ ] First draft....@alanjosephwilliams @Mr0grog @bensheldon @lippytak 
#### Other explorations
- [ ] Visualizing downtime over a year
- [ ] Visualizing downtime over a day

**Comment by lippytak** [comment]
Awesome. @alanjosephwilliams any thoughts on media plan/outreach? At the very least let's ping JA beforehand. Also x-posting with 18f, usds, and techcrunch could be valuable especially since 18f just launched https://18f.gsa.gov/2015/03/19/how-we-built-analytics-usa-gov/.

**Comment by alanjosephwilliams** [comment]
I'm definitely going to give the presentation to JA and @mollymcleod sometime next week, and incorporate their feedback. It'd be great to pull in @ZoeBlumenfeld as a copyeditor for the narrative once we have a solid draft.

I'm open to suggestions on media plan, but we have:
- a solid contact a TechCrunch
- The reporters from NYT and WaPo that covered CitizenOnboard
- Contacts at Medium that can help drive distribution.

**Comment by alanjosephwilliams** [comment]
I've updated the title of this issue to reflect the outstanding work required to publish a living write-up on the web.

The presentations in Boston and New York—which relied on a static view of uptime over the last 30 days, went over very well (great job everybody). However, the more permanent and widely-distributable write-up still feels like the primary way in which we will capture the value of the work done to date—it should remain our goal for the time being.
